services:
  airflow-webserver:
    image: apache/airflow:2.6.0
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - airflow_db:/opt/airflow
    ports:
      - "8080:8080"
    command: >
      bash -c "export AIRFLOW__CORE__EXECUTOR=SequentialExecutor &&
      airflow db init &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
      exec airflow webserver"
  
  airflow-scheduler:
    image: apache/airflow:2.6.0
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - airflow_db:/opt/airflow
    command: bash -c "export AIRFLOW__CORE__EXECUTOR=SequentialExecutor && exec airflow scheduler"

volumes:
  airflow_db:
